#%RAML 0.8
title: mg05-order-mgm-api
baseUri: http://mg05-order-mgm-api.eu.cloudhub.io/api
version: 1.0
/orders:
  displayName: orders
  get:
    description: Get list of orders for a given customer or by 
    queryParameters: 
        createdOn:
         description: Lists of orders created on this date
         required: false
        emailId: 
         description: Lists of orders created by this user
         required: false
        status:
         description: Lists of orders of this status
         required: false
    responses:
     200:
       body: 
        application/json:
         example: |
              {"Orders": [
                {"order":{
                "id":"ORD000189828",
                "products": [
                    {"id":"PROD01271","name":"prodA"},
                    {"id":"PROD09823","name":"prodB"},
                    {"id":"PROD01128","name":"prodC"}
                  ],
                "created":"08-06-2016 12:54:27 PM BST",
                "ownerid":"CUST0001",
                 "shippingaddress":{
                  "doornumber":"78",
                  "building name":"AUGUSTUS CLOSE",
                  "street":"HIGH STREET",
                  "city":"LONDON",
                  "postcode":"SK18 2SA"
                  },
                "customer":{
                  "id":"CUST0001",
                  "name":"JOHNSMITH",
                  "phone":"0222222222",
                  "email":"jsmith@testmail.com"
                  }
              }},
              {"order":{
                "id":"ORD0001123687",
                "products": [
                    {"id":"PROD01271","name":"prodX"},
                    {"id":"PROD02367","name":"prodY"},
                    {"id":"PROD04378","name":"prodZ"}
                  ],
                "created":"08-06-2016 12:54:27 PM BST",
                "ownerid":"CUST0012367",
                 "shippingaddress":{
                  "doornumber":"1",
                  "building name":"CTMS LOCK",
                  "street":"St.ANN STREET",
                  "city":"LONDON",
                  "postcode":"SK18 2SA"
                  },
                "customer":{
                  "id":"CUST0012367",
                  "name":"STEVEHARVEY",
                  "phone":"0111111111",
                  "email":"sharvey@testmail.com"
                  }
              }
              }
              ]}